#spring:
#  data:
#    mongodb:
#      host: localhost
#      database: bitky
#
#spring:
#
#  redis:
#    host: host:lml-desktop
#    port: 6379
debug: false
logging:
  level:
    root: info
server:
  port: 8080

